## Fake new classification 
Dataset1: https://www.kaggle.com/datasets/liberoliber/onion-notonion-datasets

Dataset2: https://www.kaggle.com/competitions/fake-news/data

In [2]:
import pandas as pd

In [5]:
train_data=pd.read_csv('train.csv')

In [3]:
train_data_true = pd.read_csv('Fake.csv')

In [4]:
train_data_fake = pd.read_csv('Fake.csv')

In [5]:
train_data1 = pd.concat([train_data_true,train_data_true])

In [6]:
train_data1.head()

title  \
0   Donald Trump Sends Out Embarrassing New Year’...   
1   Drunk Bragging Trump Staffer Started Russian ...   
2   Sheriff David Clarke Becomes An Internet Joke...   
3   Trump Is So Obsessed He Even Has Obama’s Name...   
4   Pope Francis Just Called Out Donald Trump Dur...   

                                                text subject  \
0  Donald Trump just couldn t wish all Americans ...    News   
1  House Intelligence Committee Chairman Devin Nu...    News   
2  On Friday, it was revealed that former Milwauk...    News   
3  On Christmas day, Donald Trump announced that ...    News   
4  Pope Francis used his annual Christmas Day mes...    News   

                date  
0  December 31, 2017  
1  December 31, 2017  
2  December 30, 2017  
3  December 29, 2017  
4  December 25, 2017

In [6]:
train_data.head()

id                                              title              author  \
0   0  House Dem Aide: We Didn’t Even See Comey’s Let...       Darrell Lucus   
1   1  FLYNN: Hillary Clinton, Big Woman on Campus - ...     Daniel J. Flynn   
2   2                  Why the Truth Might Get You Fired  Consortiumnews.com   
3   3  15 Civilians Killed In Single US Airstrike Hav...     Jessica Purkiss   
4   4  Iranian woman jailed for fictional unpublished...      Howard Portnoy   

                                                text  label  
0  House Dem Aide: We Didn’t Even See Comey’s Let...      1  
1  Ever get the feeling your life circles the rou...      0  
2  Why the Truth Might Get You Fired October 29, ...      1  
3  Videos 15 Civilians Killed In Single US Airstr...      1  
4  Print \nAn Iranian woman has been sentenced to...      1

In [7]:
train_data.isnull().sum()

id           0
title      558
author    1957
text        39
label        0
dtype: int64

In [8]:
###Drop Nan Values
train_data=train_data.dropna()


In [9]:
## Get the Independent Features

X=train_data.drop('label',axis=1)

In [10]:
## Get the Dependent features
y=train_data['label']

In [11]:
X.shape

(18285, 4)

In [12]:
y.shape

(18285,)

In [13]:
import tensorflow as tf

In [14]:
tf.__version__

'2.8.2'

In [52]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.layers import Bidirectional
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Dense

In [16]:
### Vocabulary size
voc_size=5000

### Onehot Representation

In [17]:
messages_text=X.copy()

In [18]:
messages_text['title'][1]

'FLYNN: Hillary Clinton, Big Woman on Campus - Breitbart'

In [19]:
messages_text.reset_index(inplace=True)

In [20]:
import nltk
import re
from nltk.corpus import stopwords

In [21]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [22]:
### Dataset Preprocessing
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()
corpus = []
for i in range(0, len(messages)):
    print(i)
    review = re.sub('[^a-zA-Z]', ' ', messages['title'][i])
    review = review.lower()
    review = review.split()
    
    review = [ps.stem(word) for word in review if not word in stopwords.words('english')]
    review = ' '.join(review)
    corpus.append(review)

Streaming output truncated to the last 5000 lines.
13285
13286
13287
13288
13289
13290
13291
13292
13293
13294
13295
13296
13297
13298
13299
13300
13301
13302
13303
13304
13305
13306
13307
13308
13309
13310
13311
13312
13313
13314
13315
13316
13317
13318
13319
13320
13321
13322
13323
13324
13325
13326
13327
13328
13329
13330
13331
13332
13333
13334
13335
13336
13337
13338
13339
13340
13341
13342
13343
13344
13345
13346
13347
13348
13349
13350
13351
13352
13353
13354
13355
13356
13357
13358
13359
13360
13361
13362
13363
13364
13365
13366
13367
13368
13369
13370
13371
13372
13373
13374
13375
13376
13377
13378
13379
13380
13381
13382
13383
13384
13385
13386
13387
13388
13389
13390
13391
13392
13393
13394
13395
13396
13397
13398
13399
13400
13401
13402
13403
13404
13405
13406
13407
13408
13409
13410
13411
13412
13413
13414
13415
13416
13417
13418
13419
13420
13421
13422
13423
13424
13425
13426
13427
13428
13429
13430
13431
13432
13433
13434
13435
13436
13437
13438
13439
13440
13441
13442
1

In [23]:
corpus

['hous dem aid even see comey letter jason chaffetz tweet',
 'flynn hillari clinton big woman campu breitbart',
 'truth might get fire',
 'civilian kill singl us airstrik identifi',
 'iranian woman jail fiction unpublish stori woman stone death adulteri',
 'jacki mason hollywood would love trump bomb north korea lack tran bathroom exclus video breitbart',
 'beno hamon win french socialist parti presidenti nomin new york time',
 'back channel plan ukrain russia courtesi trump associ new york time',
 'obama organ action partner soro link indivis disrupt trump agenda',
 'bbc comedi sketch real housew isi caus outrag',
 'russian research discov secret nazi militari base treasur hunter arctic photo',
 'us offici see link trump russia',
 'ye paid govern troll social media blog forum websit',
 'major leagu soccer argentin find home success new york time',
 'well fargo chief abruptli step new york time',
 'anonym donor pay million releas everyon arrest dakota access pipelin',
 'fbi close hilla

In [24]:
onehot_representation=[one_hot(words,voc_size)for words in corpus] 
onehot_representation

[[2619, 4963, 1481, 103, 4404, 4291, 2209, 1930, 3152, 3077],
 [107, 4798, 4535, 284, 4526, 4695, 4004],
 [808, 1706, 2921, 3239],
 [4153, 3507, 4429, 1619, 1013, 510],
 [4635, 4526, 1748, 3603, 2297, 2999, 4526, 4348, 3414, 4122],
 [3174,
  487,
  4099,
  1594,
  4353,
  4685,
  2507,
  258,
  2320,
  2189,
  1529,
  3591,
  2067,
  4742,
  4004],
 [4770, 3137, 1680, 1137, 2758, 396, 486, 2595, 3992, 4417, 2875],
 [4835, 2060, 2685, 4631, 3585, 4121, 4685, 2744, 3992, 4417, 2875],
 [4845, 3155, 4555, 4889, 3739, 4906, 4034, 4594, 4685, 2301],
 [580, 2725, 2339, 2802, 2177, 2120, 1334, 2957],
 [1083, 4952, 3185, 88, 4077, 4788, 1053, 4813, 984, 1253, 645],
 [1619, 2690, 4404, 4906, 4685, 3585],
 [960, 1701, 3026, 3589, 1232, 1787, 3224, 2632, 1261],
 [4019, 4292, 1175, 1939, 2722, 3254, 3056, 3992, 4417, 2875],
 [3729, 3518, 4337, 3864, 4164, 3992, 4417, 2875],
 [3551, 3043, 1251, 4896, 3540, 2058, 2910, 3490, 866, 4969],
 [3093, 1487, 4798],
 [2613, 2359, 4862, 3962, 4685, 2351, 983, 

### Embedding Representation

In [25]:
s_length=20
emb_docs=pad_sequences(onehot_representation,padding='pre',maxlen=s_length)
print(emb_docs)

[[   0    0    0 ... 1930 3152 3077]
 [   0    0    0 ... 4526 4695 4004]
 [   0    0    0 ... 1706 2921 3239]
 ...
 [   0    0    0 ... 3992 4417 2875]
 [   0    0    0 ...  118 4625  556]
 [   0    0    0 ...  558 1058 1750]]


In [26]:
emb_docs[0]

array([   0,    0,    0,    0,    0,    0,    0,    0,    0,    0, 2619,
       4963, 1481,  103, 4404, 4291, 2209, 1930, 3152, 3077], dtype=int32)

## LSTM Model

In [27]:
## Creating model
emb_vec_features=40
model_lstm=Sequential()
model_lstm.add(Embedding(voc_size,emb_vec_features,input_length=s_length))
model_lstm.add(LSTM(100))
model_lstm.add(Dense(1,activation='sigmoid'))
model_lstm.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])
print(model_lstm.summary())

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 20, 40)            200000    
                                                                 
 lstm (LSTM)                 (None, 100)               56400     
                                                                 
 dense (Dense)               (None, 1)                 101       
                                                                 
Total params: 256,501
Trainable params: 256,501
Non-trainable params: 0
_________________________________________________________________
None


In [28]:
len(emb_docs),y.shape

(18285, (18285,))

In [29]:
import numpy as np
X_final=np.array(emb_docs)
y_final=np.array(y)

In [30]:
X_final.shape,y_final.shape

((18285, 20), (18285,))

In [31]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_final, y_final, test_size=0.33, random_state=42)

### Model Training

In [46]:
### Finally Training
model_lstm.fit(X_train,y_train,validation_data=(X_test,y_test),epochs=100,batch_size=64)

Epoch 1/100
192/192 [==============================] - 3s 9ms/step - loss: 0.3380 - accuracy: 0.8380 - val_loss: 0.2038 - val_accuracy: 0.9152
Epoch 2/100
192/192 [==============================] - 1s 7ms/step - loss: 0.1557 - accuracy: 0.9388 - val_loss: 0.1935 - val_accuracy: 0.9193
Epoch 3/100
192/192 [==============================] - 1s 7ms/step - loss: 0.1141 - accuracy: 0.9577 - val_loss: 0.2500 - val_accuracy: 0.9163
Epoch 4/100
192/192 [==============================] - 1s 7ms/step - loss: 0.0835 - accuracy: 0.9710 - val_loss: 0.2484 - val_accuracy: 0.9183
Epoch 5/100
192/192 [==============================] - 1s 8ms/step - loss: 0.0661 - accuracy: 0.9770 - val_loss: 0.2781 - val_accuracy: 0.9069
Epoch 6/100
192/192 [==============================] - 1s 7ms/step - loss: 0.0472 - accuracy: 0.9851 - val_loss: 0.3103 - val_accuracy: 0.9125
Epoch 7/100
192/192 [==============================] - 1s 7ms/step - loss: 0.0369 - accuracy: 0.9877 - val_loss: 0.3926 - val_accuracy: 0.9074

### Adding Dropout 

In [33]:
from tensorflow.keras.layers import Dropout
## Creating model
embedding_vector_features=40
model_lstm=Sequential()
model_lstm.add(Embedding(voc_size,embedding_vector_features,input_length=sent_length))
model_lstm.add(Dropout(0.3))
model_lstm.add(LSTM(100))
model_lstm.add(Dropout(0.3))
model_lstm.add(Dense(1,activation='sigmoid'))
model_lstm.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])

### Performance Metrics And Accuracy

In [47]:
y_pred=model_lstm.predict(X_test)

In [36]:
from sklearn.metrics import confusion_matrix

In [48]:
threshold = 0.5
y_pred=np.where(y_pred > threshold, 1,0)

In [49]:
confusion_matrix(y_test,y_pred)

array([[3099,  320],
       [ 261, 2355]])

In [50]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.903728251864126

## Bidirectional LSTM

In [53]:
## Creating model
embedding_vector_features=40
model2=Sequential()
model2.add(Embedding(voc_size,embedding_vector_features,input_length=sent_length))
model2.add(Bidirectional(LSTM(100)))
model2.add(Dropout(0.3))
model2.add(Dense(1,activation='sigmoid'))
model2.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])
print(model2.summary())

Model: "sequential_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_3 (Embedding)     (None, 20, 40)            200000    
                                                                 
 bidirectional (Bidirectiona  (None, 200)              112800    
 l)                                                              
                                                                 
 dropout_2 (Dropout)         (None, 200)               0         
                                                                 
 dense_2 (Dense)             (None, 1)                 201       
                                                                 
Total params: 313,001
Trainable params: 313,001
Non-trainable params: 0
_________________________________________________________________
None


In [54]:
### Finally Training
model2.fit(X_train,y_train,validation_data=(X_test,y_test),epochs=100,batch_size=64)

Epoch 1/100
192/192 [==============================] - 6s 14ms/step - loss: 0.3155 - accuracy: 0.8506 - val_loss: 0.2078 - val_accuracy: 0.9170
Epoch 2/100
192/192 [==============================] - 2s 10ms/step - loss: 0.1482 - accuracy: 0.9441 - val_loss: 0.2113 - val_accuracy: 0.9185
Epoch 3/100
192/192 [==============================] - 2s 10ms/step - loss: 0.1047 - accuracy: 0.9616 - val_loss: 0.2613 - val_accuracy: 0.9099
Epoch 4/100
192/192 [==============================] - 2s 10ms/step - loss: 0.0812 - accuracy: 0.9714 - val_loss: 0.2852 - val_accuracy: 0.9147
Epoch 5/100
192/192 [==============================] - 2s 10ms/step - loss: 0.0500 - accuracy: 0.9855 - val_loss: 0.3395 - val_accuracy: 0.9162
Epoch 6/100
192/192 [==============================] - 2s 10ms/step - loss: 0.0351 - accuracy: 0.9889 - val_loss: 0.3768 - val_accuracy: 0.9118
Epoch 7/100
192/192 [==============================] - 2s 10ms/step - loss: 0.0241 - accuracy: 0.9926 - val_loss: 0.4560 - val_accuracy:

In [56]:

y_pred2=model2.predict(X_test)

In [57]:
threshold = 0.5
y_pred2=np.where(y_pred2 > threshold, 1,0)

### Performance Metrics And Accuracy

In [58]:
confusion_matrix(y_test,y_pred2)

array([[3123,  296],
       [ 283, 2333]])

In [59]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred2)

0.904059652029826

In [60]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred2))

              precision    recall  f1-score   support

           0       0.92      0.91      0.92      3419
           1       0.89      0.89      0.89      2616

    accuracy                           0.90      6035
   macro avg       0.90      0.90      0.90      6035
weighted avg       0.90      0.90      0.90      6035

